import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { createHash, createPrivateKey, randomBytes, sign } from "node:crypto";
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { symmetricDecrypt } from "better-auth/crypto";
import { bearer, emailOTP } from "better-auth/plugins";
import { createDatabase, schema, type DatabaseConnection } from "@repo/db/factory";
import { eq } from "drizzle-orm";
import { accountSecurityPlugins } from "./account-security";
import webauthnFixture from "./__fixtures__/passkey.json";

const API = "https://api.example.test";
const DASHBOARD = "https://app.example.test";
const SECRET = "account-security-integration-test-secret-00000000";
const PASSWORD = "a-test-password-that-is-long-enough";
let connection: DatabaseConnection;
let mode: "none" | "local" | "cloud" = "local";
let oauthEmail = "";
let emailCode = "";

// Public test material generated by Chromium's virtual authenticator, never an
// account credential. Keep a real none-attestation and signing key so these
// tests exercise WebAuthn verification rather than mocking its result.
const signingKey = createPrivateKey({
  key: Buffer.from(webauthnFixture.privateKey, "base64"),
  format: "der",
  type: "pkcs8",
});
const digest = (value: string | Buffer) => createHash("sha256").update(value).digest();
function registerCredential(challenge: string, origin = DASHBOARD) {
  const id = randomBytes(32);
  const original = Buffer.from(webauthnFixture.authenticatorData, "base64url");
  const authData = Buffer.from(original);
  digest(new URL(DASHBOARD).hostname).copy(authData);
  // Attested credential data follows the 37-byte authenticator header, the
  // 16-byte AAGUID and a 2-byte length. Preserve its real COSE public key.
  expect(authData.readUInt16BE(53)).toBe(id.length);
  id.copy(authData, 55);
  const attestation = Buffer.from(webauthnFixture.attestationObject, "base64url");
  const offset = attestation.indexOf(original);
  expect(offset).toBeGreaterThan(0);
  authData.copy(attestation, offset);
  return {
    name: "Test security key",
    response: {
      id: id.toString("base64url"),
      rawId: id.toString("base64url"),
      type: "public-key",
      clientExtensionResults: { credProps: { rk: true } },
      response: {
        attestationObject: attestation.toString("base64url"),
        clientDataJSON: Buffer.from(
          JSON.stringify({ type: "webauthn.create", challenge, origin }),
        ).toString("base64url"),
        transports: ["internal"],
      },
    },
  };
}

function authenticateCredential(
  id: string,
  challenge: string,
  options: { origin?: string; rpID?: string; counter?: number } = {},
) {
  const authData = Buffer.alloc(37);
  digest(options.rpID ?? new URL(DASHBOARD).hostname).copy(authData);
  authData[32] = 0x01; // User present, without claiming user verification/MFA.
  authData.writeUInt32BE(options.counter ?? 2, 33);
  const clientData = Buffer.from(
    JSON.stringify({ type: "webauthn.get", challenge, origin: options.origin ?? DASHBOARD }),
  );
  return {
    response: {
      id,
      rawId: id,
      type: "public-key",
      clientExtensionResults: {},
      response: {
        authenticatorData: authData.toString("base64url"),
        clientDataJSON: clientData.toString("base64url"),
        signature: sign(null, Buffer.concat([authData, digest(clientData)]), signingKey).toString(
          "base64url",
        ),
      },
    },
  };
}

function createAuth() {
  return betterAuth({
    baseURL: API,
    secret: SECRET,
    database: drizzleAdapter(connection.db, { provider: "pg", schema }),
    emailAndPassword: { enabled: true, revokeSessionsOnPasswordReset: true },
    trustedOrigins: [DASHBOARD],
    advanced: { cookiePrefix: "security-test" },
    session: {
      additionalFields: {
        activeOrganizationId: { type: "string", defaultValue: "test-org", input: false },
      },
      // Test the same signed-cookie cache used by the SaaS, not just DB sessions.
      cookieCache: { enabled: true },
    },
    socialProviders: {
      google: {
        clientId: "test-google-client",
        clientSecret: "test-google-secret",
        verifyIdToken: async () => true,
        getUserInfo: async () => ({
          user: { id: oauthEmail, email: oauthEmail, name: "Test user", emailVerified: true },
          data: {},
        }),
      },
    },
    plugins: [
      ...accountSecurityPlugins({ dashboardUrl: DASHBOARD, getAuthMode: async () => mode }),
      bearer(),
      emailOTP({
        async sendVerificationOTP({ otp }) {
          emailCode = otp;
        },
      }),
    ],
  });
}
let auth: ReturnType<typeof createAuth>;

class Browser {
  cookies = new Map<string, string>();
  async request(path: string, body?: unknown) {
    const response = await auth.handler(
      new Request(`${API}/api/auth${path}`, {
        method: body === undefined ? "GET" : "POST",
        headers: {
          origin: DASHBOARD,
          "content-type": "application/json",
          cookie: [...this.cookies].map(([key, value]) => `${key}=${value}`).join("; "),
        },
        ...(body === undefined ? {} : { body: JSON.stringify(body) }),
      }),
    );
    for (const cookie of response.headers.getSetCookie()) {
      const pair = cookie.split(";")[0]!;
      const index = pair.indexOf("=");
      const key = pair.slice(0, index);
      if (/max-age=0/i.test(cookie)) this.cookies.delete(key);
      else this.cookies.set(key, pair.slice(index + 1));
    }
    const text = await response.text();
    return {
      status: response.status,
      headers: response.headers,
      data: text ? JSON.parse(text) : null,
    };
  }
}

async function account() {
  const email = `security-${crypto.randomUUID()}@example.test`;
  const browser = new Browser();
  const signup = await browser.request("/sign-up/email", {
    name: "Test user",
    email,
    password: PASSWORD,
  });
  expect(signup.status).toBe(200);
  return { email, browser, id: signup.data.user.id as string };
}

async function totp(id: string) {
  const [factor] = await connection.db
    .select()
    .from(schema.twoFactor)
    .where(eq(schema.twoFactor.userId, id));
  const secret = await symmetricDecrypt({ key: SECRET, data: factor!.secret });
  return (await auth.api.generateTOTP({ body: { secret } })).code;
}

async function enroll() {
  const user = await account();
  const enabled = await user.browser.request("/two-factor/enable", { password: PASSWORD });
  expect(enabled.status).toBe(200);
  const verified = await user.browser.request("/two-factor/verify-totp", {
    code: await totp(user.id),
  });
  expect(verified.status).toBe(200);
  return { ...user, codes: enabled.data.backupCodes as string[] };
}

beforeAll(async () => {
  connection = await createDatabase({ driver: "pglite", dataDir: "memory://" });
  auth = createAuth();
}, 60_000);
afterAll(async () => connection?.close());
afterEach(() => {
  mode = "local";
  vi.restoreAllMocks();
});

describe("account security through real Better Auth HTTP endpoints", () => {
  it("requires password and authenticator confirmation, and keeps secrets out of session responses", async () => {
    const user = await account();
    expect((await user.browser.request("/two-factor/enable", { password: "wrong" })).status).toBe(
      400,
    );
    const setup = await user.browser.request("/two-factor/enable", { password: PASSWORD });
    expect(setup.status).toBe(200);
    expect(setup.data.totpURI).toMatch(/^otpauth:\/\/totp\/Openship/);
    expect(setup.data.backupCodes).toHaveLength(10);
    expect((await user.browser.request("/get-session")).data.user.twoFactorEnabled).toBe(false);
    expect(
      (await user.browser.request("/two-factor/verify-totp", { code: "invalid" })).status,
    ).toBe(401);
    expect(
      (await user.browser.request("/two-factor/verify-totp", { code: await totp(user.id) })).status,
    ).toBe(200);
    const session = await user.browser.request("/get-session");
    expect(session.data.user.twoFactorEnabled).toBe(true);
    expect(JSON.stringify(session.data)).not.toContain("backupCodes");
    expect(JSON.stringify(session.data)).not.toContain("secret");
    const [saved] = await connection.db
      .select()
      .from(schema.twoFactor)
      .where(eq(schema.twoFactor.userId, user.id));
    expect(saved!.backupCodes).not.toContain(setup.data.backupCodes[0]);
    expect((await user.browser.request("/two-factor/enable", { password: PASSWORD })).status).toBe(
      409,
    );
    expect(await totp(user.id)).toHaveLength(6);
  });

  it("issues no authenticated session or bearer token until the second factor succeeds", async () => {
    const user = await enroll();
    const browser = new Browser();
    const first = await browser.request("/sign-in/email", {
      email: user.email,
      password: PASSWORD,
    });
    expect(first.data).toEqual({ twoFactorRedirect: true });
    expect(first.headers.has("set-auth-token")).toBe(false);
    expect((await browser.request("/get-session")).data).toBeNull();
    expect((await browser.request("/passkey/list-user-passkeys")).status).toBe(401);
    expect((await browser.request("/two-factor/verify-totp", { code: "wrong" })).status).toBe(401);
    expect((await browser.request("/get-session")).data).toBeNull();
    expect(
      (await browser.request("/two-factor/verify-totp", { code: await totp(user.id) })).status,
    ).toBe(200);
    expect((await browser.request("/get-session")).data.user.id).toBe(user.id);
  });

  it("consumes a recovery code once, including competing requests, and rotates recovery codes", async () => {
    const user = await enroll();
    const browsers = [new Browser(), new Browser()];
    for (const browser of browsers)
      await browser.request("/sign-in/email", { email: user.email, password: PASSWORD });
    const results = await Promise.all(
      browsers.map((browser) =>
        browser.request("/two-factor/verify-backup-code", { code: user.codes[0] }),
      ),
    );
    expect(results.filter((result) => result.status === 200)).toHaveLength(1);
    expect(
      (await user.browser.request("/two-factor/generate-backup-codes", { password: "wrong" }))
        .status,
    ).toBe(400);
    const replacement = await user.browser.request("/two-factor/generate-backup-codes", {
      password: PASSWORD,
    });
    expect(replacement.status).toBe(200);
    expect(replacement.data.backupCodes).toHaveLength(10);
    const browser = new Browser();
    await browser.request("/sign-in/email", { email: user.email, password: PASSWORD });
    expect(
      (await browser.request("/two-factor/verify-backup-code", { code: user.codes[1] })).status,
    ).toBe(401);
    expect(
      (
        await browser.request("/two-factor/verify-backup-code", {
          code: replacement.data.backupCodes[0],
        })
      ).status,
    ).toBe(200);
  });

  it("rejects an expired pending challenge and requires a password to disable 2FA", async () => {
    const user = await enroll();
    const browser = new Browser();
    await browser.request("/sign-in/email", { email: user.email, password: PASSWORD });
    await connection.db
      .update(schema.verification)
      .set({ expiresAt: new Date(0) })
      .where(eq(schema.verification.value, user.id));
    expect(
      (await browser.request("/two-factor/verify-totp", { code: await totp(user.id) })).status,
    ).toBe(401);
    expect((await browser.request("/get-session")).data).toBeNull();
    expect((await user.browser.request("/two-factor/disable", { password: "wrong" })).status).toBe(
      400,
    );
    expect((await user.browser.request("/two-factor/disable", { password: PASSWORD })).status).toBe(
      200,
    );
    expect((await user.browser.request("/get-session")).data.user.twoFactorEnabled).toBe(false);
    expect(
      (await browser.request("/sign-in/email", { email: user.email, password: PASSWORD })).data
        .token,
    ).toBeTruthy();
  });

  it("does not let social ID-token or email-OTP sign-in bypass the second factor", async () => {
    const user = await enroll();
    oauthEmail = user.email;
    const social = new Browser();
    const result = await social.request("/sign-in/social", {
      provider: "google",
      idToken: { token: "verified-by-test-provider" },
    });
    expect(result.data).toEqual({ twoFactorRedirect: true });
    expect((await social.request("/get-session")).data).toBeNull();
    const email = new Browser();
    expect(
      (
        await email.request("/email-otp/send-verification-otp", {
          email: user.email,
          type: "sign-in",
        })
      ).status,
    ).toBe(200);
    expect(
      (await email.request("/sign-in/email-otp", { email: user.email, otp: emailCode })).data,
    ).toEqual({ twoFactorRedirect: true });
    expect((await email.request("/get-session")).data).toBeNull();
  });

  it("preserves an OAuth continuation only after the second factor", async () => {
    const user = await enroll();
    oauthEmail = user.email;
    vi.spyOn(globalThis, "fetch").mockImplementation(async () =>
      Response.json({
        access_token: "test-access-token",
        token_type: "Bearer",
        expires_in: 3600,
      }),
    );
    const browser = new Browser();
    const continuation = `${DASHBOARD}/mcp/authorize?client_id=test-client`;
    const start = await browser.request("/sign-in/social", {
      provider: "google",
      callbackURL: continuation,
    });
    const state = new URL(start.data.url).searchParams.get("state");
    const callback = await browser.request(
      `/callback/google?code=test-code&state=${encodeURIComponent(state!)}`,
    );
    expect(callback.status).toBe(302);
    expect(callback.headers.get("location")).toBe(`${DASHBOARD}/two-factor`);
    expect((await browser.request("/get-session")).data).toBeNull();
    const verified = await browser.request("/two-factor/verify-totp", {
      code: await totp(user.id),
    });
    expect(verified.data.redirectURL).toBe(continuation);
    expect((await browser.request("/get-session")).data.user.id).toBe(user.id);
  });

  it("lets a freshly signed-in OAuth-only user set a password, without overwriting an existing one", async () => {
    oauthEmail = `oauth-${crypto.randomUUID()}@example.test`;
    const browser = new Browser();
    expect(
      (await browser.request("/sign-in/social", { provider: "google", idToken: { token: "test" } }))
        .status,
    ).toBe(200);
    expect(
      (await browser.request("/account-security/set-password", { newPassword: "short" })).status,
    ).toBe(400);
    expect(
      (await browser.request("/account-security/set-password", { newPassword: PASSWORD })).status,
    ).toBe(200);
    expect(
      (
        await browser.request("/account-security/set-password", {
          newPassword: "different-long-password",
        })
      ).status,
    ).toBe(400);
    expect((await browser.request("/two-factor/enable", { password: PASSWORD })).status).toBe(200);
    expect(
      (await new Browser().request("/account-security/set-password", { newPassword: PASSWORD }))
        .status,
    ).toBe(401);
  });

  it("registers a real WebAuthn credential and requires 2FA after passkey sign-in", async () => {
    const user = await enroll();
    const options = await user.browser.request("/passkey/generate-register-options");
    expect(options.data.rp.id).toBe("app.example.test");
    expect(options.data.authenticatorSelection.residentKey).toBe("required");
    const credential = registerCredential(options.data.challenge);
    const registered = await user.browser.request("/passkey/verify-registration", credential);
    expect(registered.status).toBe(200);
    expect(registered.data.userId).toBe(user.id);

    const other = await account();
    expect((await other.browser.request("/passkey/list-user-passkeys")).data).toEqual([]);
    expect(
      (await other.browser.request("/passkey/delete-passkey", { id: registered.data.id })).status,
    ).toBe(401);
    expect(
      (
        await other.browser.request("/passkey/update-passkey", {
          id: registered.data.id,
          name: "Stolen",
        })
      ).status,
    ).toBe(401);
    expect(
      (
        await user.browser.request("/passkey/update-passkey", {
          id: registered.data.id,
          name: "x".repeat(81),
        })
      ).status,
    ).toBe(400);

    const browser = new Browser();
    const login = await browser.request("/passkey/generate-authenticate-options");
    const assertion = authenticateCredential(credential.response.id, login.data.challenge);
    const result = await browser.request("/passkey/verify-authentication", assertion);
    expect(result.data).toEqual({ twoFactorRedirect: true });
    expect(result.headers.has("set-auth-token")).toBe(false);
    expect((await browser.request("/get-session")).data).toBeNull();
    expect((await browser.request("/passkey/verify-authentication", assertion)).status).toBe(400);
    expect(
      (await browser.request("/two-factor/verify-backup-code", { code: user.codes[0] })).status,
    ).toBe(200);
    expect((await browser.request("/get-session")).data.user.id).toBe(user.id);
    expect(
      (await user.browser.request("/passkey/delete-passkey", { id: registered.data.id })).status,
    ).toBe(200);
  });

  it("rejects wrong WebAuthn origins, RP IDs, expired challenges and reused assertions", async () => {
    const user = await account();
    const options = await user.browser.request("/passkey/generate-register-options");
    expect(
      (
        await user.browser.request(
          "/passkey/verify-registration",
          registerCredential(options.data.challenge, API),
        )
      ).status,
    ).not.toBe(200);
    const credential = registerCredential(options.data.challenge);
    expect((await user.browser.request("/passkey/verify-registration", credential)).status).toBe(
      200,
    );
    expect((await user.browser.request("/passkey/verify-registration", credential)).status).toBe(
      400,
    );

    const browser = new Browser();
    const login = await browser.request("/passkey/generate-authenticate-options");
    for (const invalid of [{ origin: API }, { rpID: "api.example.test" }]) {
      expect(
        (
          await browser.request(
            "/passkey/verify-authentication",
            authenticateCredential(credential.response.id, login.data.challenge, invalid),
          )
        ).status,
      ).toBe(400);
      expect((await browser.request("/get-session")).data).toBeNull();
    }
    const record = (await connection.db.select().from(schema.verification)).find((row) =>
      row.value.includes(login.data.challenge),
    );
    expect(record).toBeDefined();
    await connection.db
      .update(schema.verification)
      .set({ expiresAt: new Date(0) })
      .where(eq(schema.verification.id, record!.id));
    expect(
      (
        await browser.request(
          "/passkey/verify-authentication",
          authenticateCredential(credential.response.id, login.data.challenge),
        )
      ).status,
    ).toBe(400);
    expect((await browser.request("/get-session")).data).toBeNull();

    const fresh = await browser.request("/passkey/generate-authenticate-options");
    const assertion = authenticateCredential(credential.response.id, fresh.data.challenge);
    expect((await browser.request("/passkey/verify-authentication", assertion)).status).toBe(200);
    expect((await browser.request("/get-session")).data.user.id).toBe(user.id);
    const replay = new Browser();
    const next = await replay.request("/passkey/generate-authenticate-options");
    expect((await replay.request("/passkey/verify-authentication", assertion)).status).toBe(400);
    expect(
      (
        await replay.request(
          "/passkey/verify-authentication",
          authenticateCredential(credential.response.id, next.data.challenge),
        )
      ).status,
    ).toBe(400);
    expect((await replay.request("/get-session")).data).toBeNull();
  });

  it("rejects revoked cached sessions for security management and stale sessions for a first password", async () => {
    const user = await enroll();
    await connection.db.delete(schema.session).where(eq(schema.session.userId, user.id));
    for (const [path, body] of [
      ["/two-factor/disable", { password: PASSWORD }],
      ["/two-factor/enable", { password: PASSWORD }],
      ["/two-factor/generate-backup-codes", { password: PASSWORD }],
      ["/passkey/generate-register-options", undefined],
    ] as const)
      expect((await user.browser.request(path, body)).status).toBe(401);

    oauthEmail = `stale-oauth-${crypto.randomUUID()}@example.test`;
    const browser = new Browser();
    const signedIn = await browser.request("/sign-in/social", {
      provider: "google",
      idToken: { token: "test" },
    });
    const old = new Date(Date.now() - 172_800_000);
    await connection.db
      .update(schema.session)
      .set({ createdAt: old, updatedAt: old })
      .where(eq(schema.session.userId, signedIn.data.user.id));
    expect(
      (await browser.request("/account-security/set-password", { newPassword: PASSWORD })).status,
    ).toBe(403);
  });

  it("preserves 2FA through an email-code password reset", async () => {
    const user = await enroll();
    const browser = new Browser();
    expect(
      (
        await browser.request("/email-otp/send-verification-otp", {
          email: user.email,
          type: "forget-password",
        })
      ).status,
    ).toBe(200);
    const password = "new-password-after-recovery";
    expect(
      (
        await browser.request("/email-otp/reset-password", {
          email: user.email,
          otp: emailCode,
          password,
        })
      ).status,
    ).toBe(200);
    expect((await browser.request("/get-session")).data).toBeNull();
    expect((await browser.request("/sign-in/email", { email: user.email, password })).data).toEqual(
      { twoFactorRedirect: true },
    );
    expect((await browser.request("/get-session")).data).toBeNull();
    expect(
      (await browser.request("/two-factor/verify-backup-code", { code: user.codes[0] })).status,
    ).toBe(200);
  });

  it.each(["none", "cloud"] as const)(
    "does not enable local account security in %s mode",
    async (authMode) => {
      const user = await account();
      mode = authMode;
      for (const [path, body] of [
        ["/two-factor/enable", { password: PASSWORD }],
        ["/account-security/set-password", { newPassword: PASSWORD }],
        ["/passkey/generate-register-options", undefined],
        ["/passkey/generate-authenticate-options", undefined],
      ] as const)
        expect((await user.browser.request(path, body)).status).toBe(403);
    },
  );
});
