import { createAuthClient } from "better-auth/react";
import { organizationClient, emailOTPClient, twoFactorClient } from "better-auth/client/plugins";
import { passkeyClient } from "@better-auth/passkey/client";
import { getAuthBaseUrl } from "@/lib/api/urls";

/**
 * API base URL - auth requests go directly to the selected API origin.
 *
 * Local SaaS uses localhost:4100. Public-host dev and production use
 * api.openship.io so Better Auth can share cookies with app.openship.io.
 */
const AUTH_BASE_URL = getAuthBaseUrl();

export const authClient = createAuthClient({
  baseURL: AUTH_BASE_URL,
  fetchOptions: {
    credentials: "include",
    // Disable retry to prevent infinite loops on 429
    retry: {
      type: "linear",
      attempts: 0,
      delay: 0,
    },
  },
  plugins: [organizationClient(), emailOTPClient(), passkeyClient(), twoFactorClient()],
});

/** Password creation for a freshly authenticated OAuth-only account. */
export function setAccountPassword(newPassword: string) {
  return authClient.$fetch<{ status: boolean }>("/account-security/set-password", {
    method: "POST", body: { newPassword },
  });
}

export const {
  signIn,
  signUp,
  signOut,
  useSession,
} = authClient;

/**
 * Email-OTP helpers (code-based email verification). Proxy-generated by Better
 * Auth from the emailOTP plugin endpoints; accessed via the client object so TS
 * doesn't complain about missing static properties (same pattern as below).
 *   verifyEmail          → POST /email-otp/verify-email        ({ email, otp })
 *   sendVerificationOtp  → POST /email-otp/send-verification-otp ({ email, type })
 */
export const emailOtp = (authClient as any).emailOtp as {
  verifyEmail: (data: { email: string; otp: string }) => Promise<{
    data?: unknown;
    error?: { message?: string; code?: string } | null;
  }>;
  sendVerificationOtp: (data: {
    email: string;
    type: "email-verification" | "sign-in" | "forget-password";
  }) => Promise<{ data?: unknown; error?: { message?: string; code?: string } | null }>;
  /**
   * Reset a password with a code instead of a link — POST /email-otp/reset-password.
   *
   * The link flow (`resetPassword` below, with a `token` from the URL) is retired: a
   * "click here to change your password" URL is the most phishing-shaped mail the
   * product sends, and gateways score and rewrite it. `resetPassword` is kept
   * exported only so an old link already sitting in someone's inbox still works.
   */
  resetPassword: (data: { email: string; otp: string; password: string }) => Promise<{
    data?: unknown;
    error?: { message?: string; code?: string } | null;
  }>;
};

/**
 * Email / password helpers - these are proxy-generated by Better Auth
 * when the server has emailAndPassword enabled. We access them via
 * the client object so TypeScript doesn't complain about missing
 * static properties.
 */
// No `requestPasswordReset` helper any more: starting a reset means SENDING A CODE,
// which is `emailOtp.sendVerificationOtp({ type: "forget-password" })` above. The
// link-issuing endpoint is deliberately unreachable from the client — leaving a
// helper for it invites a caller that mails a link nobody can act on, since the
// server no longer defines `sendResetPassword`.
//
// `resetPassword` (token) stays only so a reset email already in someone's inbox
// still completes; the code path is `emailOtp.resetPassword`.
export const resetPassword = (authClient as any).resetPassword as (
  opts: { newPassword: string; token?: string },
) => Promise<{ error?: { message?: string } }>;

export const sendVerificationEmail = (authClient as any).sendVerificationEmail as (
  opts: { email: string; callbackURL?: string },
) => Promise<{ error?: { message?: string } }>;

export const verifyEmail = (authClient as any).verifyEmail as (
  opts: { query: { token: string } },
) => Promise<{ error?: { message?: string } }>;
